// File/folder naming for the customer package — see CLAUDE.md's "File
// naming convention". Pure string logic so tracklist.js, labels.js and
// cover.js/inner-sleeve.js/inlay.js all build the exact same name for the exact same file,
// which is what lets a reopened project zip re-attach files by an exact
// name match instead of guessing.
//
// Versioning isn't tracked yet (see CLAUDE.md) — every name gets a fixed
// "v1" suffix for now.

// German umlauts/ß transliterated before the general a-z/0-9 filter below
// would otherwise just drop them as unrecognized characters — "schöner"
// should become "schoener", not "sch_ner".
const GERMAN_TRANSLITERATIONS = { "ä":"ae", "ö":"oe", "ü":"ue", "ß":"ss" };

// Lowercase, filename-safe token: anything that isn't a-z/0-9 collapses
// to one underscore, leading/trailing underscores trimmed.
export function slug(str){
  return (str || "")
    .toLowerCase()
    .replace(/[äöüß]/g, ch => GERMAN_TRANSLITERATIONS[ch])
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

// The file extension including its leading dot, or "" if there isn't one.
export function fileExt(name){
  return name && name.includes(".") ? name.slice(name.lastIndexOf(".")) : "";
}

// Filesystem-safe name — strips path separators and reserved
// Windows/macOS filename characters. Used for names that keep mixed case
// (catalogue numbers), unlike slug() which also lowercases.
export function sanitizeFileName(name){
  return (name || "").trim().replace(/[\\/:*?"<>|]+/g, "-") || "untitled-release";
}

// A File picked via <input type=file> gets its MIME type from the OS.
// A File reconstructed from a reopened zip's raw bytes (see tracklist.js
// loadProject) doesn't — without it, the browser has nothing to render a
// PDF/image preview with and an <iframe>/<img> just shows raw bytes.
const MIME_BY_EXT = {
  ".pdf": "application/pdf",
  ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
  ".tif": "image/tiff", ".tiff": "image/tiff",
  ".wav": "audio/wav", ".wave": "audio/wav",
  ".aif": "audio/aiff", ".aiff": "audio/aiff", ".aifc": "audio/aiff",
  ".txt": "text/plain"
};
export function mimeType(ext){
  return MIME_BY_EXT[(ext || "").toLowerCase()] || "";
}

// PNKRCK007_A1_my_way_artist_v1.wav — catalogue# prefixed so a track
// keeps a unique name once it's pulled out of its project folder (e.g.
// into a shared mastering working directory), same reasoning as
// printedPartFileName below.
export function trackFileName({catalogue, side, index, title, artist, ext}){
  const parts = [sanitizeFileName(catalogue), side + index, slug(title) || "untitled"];
  if(artist && slug(artist)) parts.push(slug(artist));
  return parts.join("_") + "_v1" + ext;
}

// PNKRCK007_A_side_v1.wav — a whole side delivered as one continuous file.
export function continuousSideFileName({catalogue, side, ext}){
  return sanitizeFileName(catalogue) + "_" + side + "_side_v1" + ext;
}

// PNKRCK007_tracklist_A_v1.txt — the customer's own tracklist/cuesheet
// for a side delivered as one continuous audio file, uploaded instead of
// (or alongside) manually entering the track rows.
export function tracklistFileName({catalogue, side, ext}){
  return sanitizeFileName(catalogue) + "_tracklist_" + side + "_v1" + ext;
}

// PNKRCK007_labels_A_v1.pdf / PNKRCK007_cover_v1.pdf
export function printedPartFileName({catalogue, part, variant, ext}){
  const parts = [sanitizeFileName(catalogue), part];
  if(variant) parts.push(variant);
  return parts.join("_") + "_v1" + ext;
}

// PNKRCK007_labels_A_v1_preview.jpg — same base name as
// printedPartFileName, forced to a .jpg preview. Generated by the
// plant's backend (not this tool) once it reviews the real file;
// recognized automatically on the next project reload via the
// existing fileMap-by-exact-name mechanism in loadProject (see
// tracklist.js).
export function previewFileName({catalogue, part, variant}){
  const parts = [sanitizeFileName(catalogue), part];
  if(variant) parts.push(variant);
  return parts.join("_") + "_v1_preview.jpg";
}

// YYMMDD, local date.
export function dateStamp(date = new Date()){
  const yy = String(date.getFullYear()).slice(-2);
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  return yy + mm + dd;
}

// yyyy-mm-dd, local date — human-readable, for document headers, as
// opposed to dateStamp()'s compact form used in filenames.
export function humanDate(date = new Date()){
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

// 260919_PNKRCK007_customer_example_com — the project package's file
// name (also the single folder nested inside the zip).
export function projectFileName({catalogue, customerEmail, date}){
  const parts = [dateStamp(date), sanitizeFileName(catalogue)];
  if(customerEmail && slug(customerEmail)) parts.push(slug(customerEmail));
  return parts.join("_");
}
